### ISSUE TITLE
Unable to build docker image

### ISSUE THREAD

**Issue by algaebrown** [TF-Chan-Lab/rG4-seeker#1]
```
sudo singularity build rg4.simg rg4_seeker.docker.tar.gz 
[sudo] password for hermuba: 
?\?$,GdyAD?????_?E?C????????t rg4_seeker.docker.tar.gz: while parsing definition: rg4_seeker.docker.tar.gz: failed to parse deffile header: header key??J^rG4_seeker.docker.tar?zy??ڶ???O???=?ET?㬈8????,2ʠ????ʪ3?ׯ?莸DF????k^??2??rXN̡???ӂ??bY4?sr??K???f8?ϋ9	
????_???k?????,?s??X?????q]???߾?ߺ??_?؜ had no val       Yq,???}?j?g??????[?ϛ?Ig8??3?e?c??O?G???? ????????
```
I downloaded the docker image from the drive link but it seems the file is deprecated?
Thanks

**Comment by eugenechow** [comment]
Hi, thanks for raising this issue.

We just verified the Google Drive link and tested the image in a more recent version of Docker (version 20.10.7, build f0df350, on Ubuntu 18.04). Everything worked fine, so I am quite sure the image is not deprecated.

Regarding the error message, it looks to me that a compressed data stream is fed to a program which does not expect compressed input. I believe "Singularity build" does not accept images in .tar.gz format.

And btw, since you already have sudo access to the PC/server, maybe you can just run our docker image on Docker?

**Comment by algaebrown** [comment]
Thank you so much for the timely reply. I don't have sudo on the server. It was my local machine. However I managed to install using `pip install`
